### ISSUE TITLE
[Bug] rem/em not being parsed correctly on native 

### ISSUE THREAD

**Issue by marklawlor** [marklawlor/tailwindcss-react-native#10]
The `postcss-rem-to-pixel` doesn't appear to be working in all instances. Additionally it only does `rem`. 

`tailwind-rn` use their own [rex-to-px](https://github.com/vadimdemedes/tailwind-rn/blob/master/source/lib/rem-to-px.ts) and [ex-to-px transform](https://github.com/vadimdemedes/tailwind-rn/blob/master/source/lib/em-to-px.ts). We might have to do the same thing - however I would like to fix it via a `postcss` plugin

**Comment by jmeistrich** [comment]
I just encountered this too, using `my-8` (for example).

**Comment by marklawlor** [comment]
I think I'll need to write a custom css transform library to solve this. I was hoping that `css-to-react-native` and some postcss plugins would solve the issue, but it doesn't seem to be the case.

In the mean time, the work around is to use arbitrary values eg `my-[20px]`

**Comment by marklawlor** [comment]
Vanilla tailwindcss styles (eg `my-8`) will now work on version `0.0.21`. Arbitrary styles using `em`/`rem` are not supported on native. They currently error with a not great error message, but in a future feature we'll provide warnings if you are trying to use an unsupported unit for the platform eg `Native does not support unit rem. Consider adding a platform prefix or separating this component into different platform files.`
