### ISSUE TITLE
[Bug] Crashes without tailwindcss and tailwind.config.js

### ISSUE THREAD

**Issue by jmeistrich** [marklawlor/tailwindcss-react-native#11]
I see that `tailwindcss` is a peer dependency, but I think the docs should mention both steps:
1. Install tailwindcss package
2. Create a tailwind.config.js file. Does it need to have defaults set up? It seems to work for me when it's just an empty file. So maybe the plugin can work even if there is no config file?

**Comment by marklawlor** [comment]
Fixed in `0.0.17`.
