### ISSUE TITLE
[Docs] "Rendered more hooks" error - cavats & workarounds

### ISSUE THREAD

**Issue by jmeistrich** [marklawlor/tailwindcss-react-native#12]
Adding a className or removing a className prop crashes with a "Rendered more hooks than expected" (or fewer) error in the Fast Refresh. I'm not sure how you'd solve it though, because you wouldn't want to use the hook on all components...

**Comment by marklawlor** [comment]
Yes, this is related to this issue https://github.com/marklawlor/tailwindcss-react-native/issues/2 and needs documentation.

If you have a conditional className, don't remove the className attribute simply pass it an empty string (undefined & null also work in `0.0.17`. For every className attribute a hook is inserted - you need to keep the attribute there so the hook remains.

There are some other scenarios that you'll encounter (eg looping over lists) that face a similar problem. I'll have the documentation up for them _soon_

**Comment by marklawlor** [comment]
This was significantly improved in `0.0.19`. I'm going to close this and track the documentation under #2
