### ISSUE TITLE
[Docs] Add docs for NextJS

### ISSUE THREAD

**Issue by jmeistrich** [marklawlor/tailwindcss-react-native#13]
I get two (I think related) errors on react-native-web:
```
error - ./node_modules/tailwindcss-react-native/dist/provider.jsx
Module parse failed: Unexpected token (8:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const [styleValue] = useState({ media, styles });
|     const [colorScheme, setColorScheme] = useState(Appearance.getColorScheme() ?? "light");
>     return (<TailwindStyleContext.Provider value={styleValue}>
|       <TailwindColorSchemeContext.Provider value={overrideColorScheme || colorScheme}>
|         <TailwindSetColorSchemeContext.Provider value={setColorScheme}>
(node:41732) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
```
and
```
error - SyntaxError: Unexpected token 'export'
```

I think this may be because of my tsconfig settings, but next.js enforces `module: esnext` and `jsx: preserve`. Here's my tsconfig:
```
{
  "compilerOptions": {
    "target": "ES2018",
    "lib": [
      "dom",
      "dom.iterable",
      "es2019",
      "esnext"
    ],
    "experimentalDecorators": true, /* Enables experimental support for ES7 decorators. */
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "incremental": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "baseUrl": ".",
    "rootDirs": [
      "./src",
      "../common/"
    ],
    "paths": {
      "*": [
        "./node_modules/*"
      ],
      "~/*": [
        "./src/*"
      ],
      "common/*": [
        "../common/*"
      ]
    }
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "../common/*"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by marklawlor** [comment]
You will need to add `tailwindcss-react-native` to your `next-transpile-modules` inside your `next.config.js`.

**Comment by jmeistrich** [comment]
That worked, thanks. And I also needed to add this library's dependency `@react-native-community/hooks`. So this is a working solution in next.config.js:

```
const withTM = require('next-transpile-modules')(['tailwindcss-react-native', '@react-native-community/hooks']);

module.exports = withTM({
    webpack: (config) => {
        config.resolve.alias = {
            ...(config.resolve.alias || {}),
            // Transform all direct `react-native` imports to `react-native-web`
            'react-native$': 'react-native-web',
        };
        config.resolve.extensions = ['.web.js', '.web.jsx', '.web.ts', '.web.tsx', ...config.resolve.extensions];
    },
});

})

**Comment by marklawlor** [comment]
Renaming this issue to track the documentation of setting up NextJS (both via webpack & via `@expo/next-adapter`)

**Comment by jmeistrich** [comment]
I'll add another step I had to do to get NextJS working, for your reference. The [example](https://github.com/vercel/next.js/blob/main/examples/with-react-native-web/pages/_document.js) I started from adds the React Native styles with getStyleElement() to the end of the page. But that puts it after the tailwindcss import, which then overrides some of the styles (like margin).

I'm new to react-native-web (but very experienced with reactjs and react-native) so I'm not sure of the correct solution, but it still seems to work fine if I remove the addition of getStyleElement(), and it fixes the problem.

**Comment by marklawlor** [comment]
There a couple of solutions to this, but I think the easiest one is to increase the specificity of the tailwind styles via the `important` tailwind config option.

https://github.com/marklawlor/solito-tailwind/blob/main/apps/next/tailwind.config.js#L8

**Comment by jmeistrich** [comment]
Cool, I didn't know about that option. That works and seems like a better solution.

**Comment by marklawlor** [comment]
Docs are now live: https://tailwindcss-react-native.vercel.app/
