### ISSUE TITLE
The project's Babel config is invalid: Cannot find module 'tailwindcss'

### ISSUE THREAD

**Issue by galacoder** [marklawlor/tailwindcss-react-native#19]
Hi there,

I love tailwind so much and have been looking around to find a better solution than tailwind-rn for my react native apps. I found tailwindcss-react-native and am so eager to try it out. However, I got an issue when trying to install it with expo. Please check the attachment and advise!

<img width="1237" alt="Screen Shot 2022-04-07 at 20 24 39" src="https://user-images.githubusercontent.com/13715145/162209613-560da94f-48ec-4b90-8ac8-7d2c00d394d0.png">
[test tailwind-react-native.zip](https://github.com/marklawlor/tailwindcss-react-native/files/8443203/test.tailwind-react-native.zip)

**Comment by jmeistrich** [comment]
I think the issue you're seeing is that this library has a peer dependency of the tailwindcss package. You can install it with `npm install tailwindcss` or `yarn add tailwindcss`.

**Comment by marklawlor** [comment]
I think at the time of this issue, the current version of NPM didn't have the peerDependancy section in its readme but `npm`/ `yarn` should have reported that it is required during installation.

Either way, I've updated the docs to include `tailwindcss` in the install command incase people miss the message from their package manager and published a new version (with the updated readme) to NPM

**Comment by Olayinka19** [comment]
Hello guys i tried the npm install tailwindcss still did not work
