### ISSUE TITLE
[Docs] Rules of hooks

### ISSUE THREAD

**Issue by marklawlor** [marklawlor/tailwindcss-react-native#2]
`tailwindcss-native-react` must follow the [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html). This may not be immediately obvious to new users and should be documented.

**Comment by marklawlor** [comment]
Added basic docs to the readme.

**Comment by jmeistrich** [comment]
Nice, that should be very helpful. Can I suggest adding one more point about the "Rendered more hooks than expected" error so new users don't get scared/confused by it?
