### ISSUE TITLE
[Tests] 100% Tailwindcss coverage

### ISSUE THREAD

**Issue by marklawlor** [marklawlor/tailwindcss-react-native#22]
The initial version of this library simply turned off core tailwindcss plugins only enabled ones could compile "as-is" to React Native. This approach was a bit naive and we should be able to more core plugins through a combination of (in order of preference)

- Better base theme
- Post processing styles
- Custom plugins. 

This is a little bit of tedious task, but we should be able to write a until test for each Tailwind style to ensure maximum compatibility.

This is a todo list that each section of the tailwind website has both a unit test and an entry in the compatibility document.

**This is not a list of what works, rather what has been unit tested and documented** 

Layout

- [x] [Aspect Ratio](https://tailwindcss.com/docs/aspect-ratio)
- [x] [Container](https://tailwindcss.com/docs/container)
- [x] [Columns](https://tailwindcss.com/docs/columns)
- [x] [Break After](https://tailwindcss.com/docs/break-after)
- [x] [Break Before](https://tailwindcss.com/docs/break-before)
- [x] [Break Inside](https://tailwindcss.com/docs/break-inside)
- [x] [Box Decoration Break](https://tailwindcss.com/docs/box-decoration-break)
- [x] [Box Sizing](https://tailwindcss.com/docs/box-sizing)
- [x] [Display](https://tailwindcss.com/docs/display)
- [x] [Floats](https://tailwindcss.com/docs/float)
- [x] [Clear](https://tailwindcss.com/docs/clear)
- [x] [Isolation](https://tailwindcss.com/docs/isolation)
- [x] [Object Fit](https://tailwindcss.com/docs/object-fit)
- [x] [Object Position](https://tailwindcss.com/docs/object-position)
- [x] [Overflow](https://tailwindcss.com/docs/overflow)
- [x] [Overscroll Behavior](https://tailwindcss.com/docs/overscroll-behavior)
- [x] [Position](https://tailwindcss.com/docs/position)
- [x] [Top / Right / Bottom / Left](https://tailwindcss.com/docs/top-right-bottom-left)
- [x] [Visibility](https://tailwindcss.com/docs/visibility)
- [x] [Z-Index](https://tailwindcss.com/docs/z-index)

Flexbox & Grid

- [x] [Flex Basis](https://tailwindcss.com/docs/flex-basis)
- [x] [Flex Direction](https://tailwindcss.com/docs/flex-direction)
- [x] [Flex Wrap](https://tailwindcss.com/docs/flex-wrap)
- [ ] [Flex](https://tailwindcss.com/docs/flex)
- [x] [Flex Grow](https://tailwindcss.com/docs/flex-grow)
- [x] [Flex Shrink](https://tailwindcss.com/docs/flex-shrink)
- [x] [Order](https://tailwindcss.com/docs/order)
- [x] [Grid Template Columns](https://tailwindcss.com/docs/grid-template-columns)
- [x] [Grid Column Start / End](https://tailwindcss.com/docs/grid-column)
- [x] [Grid Template Rows](https://tailwindcss.com/docs/grid-template-rows)
- [x] [Grid Row Start / End](https://tailwindcss.com/docs/grid-row)
- [x] [Grid Auto Flow](https://tailwindcss.com/docs/grid-auto-flow)
- [x] [Grid Auto Columns](https://tailwindcss.com/docs/grid-auto-columns)
- [x] [Grid Auto Rows](https://tailwindcss.com/docs/grid-auto-rows)
- [x] [Gap](https://tailwindcss.com/docs/gap)
- [x] [Justify Content](https://tailwindcss.com/docs/justify-content)
- [x] [Justify Items](https://tailwindcss.com/docs/justify-items)
- [x] [Justify Self](https://tailwindcss.com/docs/justify-self)
- [x] [Align Content](https://tailwindcss.com/docs/align-content)
- [x] [Align Items](https://tailwindcss.com/docs/align-items)
- [x] [Align Self](https://tailwindcss.com/docs/align-self)
- [ ] [Place Content](https://tailwindcss.com/docs/place-content)
- [x] [Place Items](https://tailwindcss.com/docs/place-items)
- [x] [Place Self](https://tailwindcss.com/docs/place-self)

Spacing

- [x] [Padding](https://tailwindcss.com/docs/padding)
- [x] [Margin](https://tailwindcss.com/docs/margin)
- [x] [Space Between](https://tailwindcss.com/docs/space)

Sizing

- [x] [Width](https://tailwindcss.com/docs/width)
- [x] [Min-Width](https://tailwindcss.com/docs/min-width)
- [x] [Max-Width](https://tailwindcss.com/docs/max-width)
- [x] [Height](https://tailwindcss.com/docs/height)
- [x] [Min-Height](https://tailwindcss.com/docs/min-height)
- [x] [Max-Height](https://tailwindcss.com/docs/max-height)

Typography

- [x] [Font Family](https://tailwindcss.com/docs/font-family)
- [x] [Font Size](https://tailwindcss.com/docs/font-size)
- [x] [Font Smoothing](https://tailwindcss.com/docs/font-smoothing)
- [x] [Font Style](https://tailwindcss.com/docs/font-style)
- [x] [Font Weight](https://tailwindcss.com/docs/font-weight)
- [ ] [Font Variant Numeric](https://tailwindcss.com/docs/font-variant-numeric)
- [x] [Letter Spacing](https://tailwindcss.com/docs/letter-spacing)
- [x] [Line Height](https://tailwindcss.com/docs/line-height)
- [x] [List Style Type](https://tailwindcss.com/docs/list-style-type)
- [x] [List Style Position](https://tailwindcss.com/docs/list-style-position)
- [x] [Text Align](https://tailwindcss.com/docs/text-align)
- [x] [Text Color](https://tailwindcss.com/docs/text-color)
- [x] [Text Decoration](https://tailwindcss.com/docs/text-decoration)
- [x] [Text Decoration Color](https://tailwindcss.com/docs/text-decoration-color)
- [x] [Text Decoration Style](https://tailwindcss.com/docs/text-decoration-style)
- [x] [Text Decoration Thickness](https://tailwindcss.com/docs/text-decoration-thickness)
- [x] [Text Underline Offset](https://tailwindcss.com/docs/text-underline-offset)
- [x] [Text Transform](https://tailwindcss.com/docs/text-transform)
- [ ] [Text Overflow](https://tailwindcss.com/docs/text-overflow)
- [x] [Text Indent](https://tailwindcss.com/docs/text-indent)
- [x] [Vertical Align](https://tailwindcss.com/docs/vertical-align)
- [x] [Whitespace](https://tailwindcss.com/docs/whitespace)
- [x] [Word Break](https://tailwindcss.com/docs/word-break)
- [x] [Content](https://tailwindcss.com/docs/content)

Backgrounds

- [x] [Background Attachment](https://tailwindcss.com/docs/background-attachment)
- [x] [Background Clip](https://tailwindcss.com/docs/background-clip)
- [x] [Background Color](https://tailwindcss.com/docs/background-color)
- [x] [Background Origin](https://tailwindcss.com/docs/background-origin)
- [x] [Background Position](https://tailwindcss.com/docs/background-position)
- [x] [Background Repeat](https://tailwindcss.com/docs/background-repeat)
- [x] [Background Size](https://tailwindcss.com/docs/background-size)
- [x] [Background Image](https://tailwindcss.com/docs/background-image)
- [x] [Gradient Color Stops](https://tailwindcss.com/docs/gradient-color-stops)

Borders

- [x] [Border Radius](https://tailwindcss.com/docs/border-radius)
- [x] [Border Width](https://tailwindcss.com/docs/border-width)
- [x] [Border Color](https://tailwindcss.com/docs/border-color)
- [x] [Border Style](https://tailwindcss.com/docs/border-style)
- [x] [Divide Width](https://tailwindcss.com/docs/divide-width)
- [x] [Divide Color](https://tailwindcss.com/docs/divide-color)
- [x] [Divide Style](https://tailwindcss.com/docs/divide-style)
- [ ] [Outline Width](https://tailwindcss.com/docs/outline-width)
- [ ] [Outline Color](https://tailwindcss.com/docs/outline-color)
- [ ] [Outline Style](https://tailwindcss.com/docs/outline-style)
- [ ] [Outline Offset](https://tailwindcss.com/docs/outline-offset)
- [ ] [Ring Width](https://tailwindcss.com/docs/ring-width)
- [ ] [Ring Color](https://tailwindcss.com/docs/ring-color)
- [ ] [Ring Offset Width](https://tailwindcss.com/docs/ring-offset-width)
- [ ] [Ring Offset Color](https://tailwindcss.com/docs/ring-offset-color)

Effects

- [x] [Box Shadow](https://tailwindcss.com/docs/box-shadow)
- [ ] [Box Shadow Color](https://tailwindcss.com/docs/box-shadow-color)
- [x] [Opacity](https://tailwindcss.com/docs/opacity)
- [x] [Mix Blend Mode](https://tailwindcss.com/docs/mix-blend-mode)
- [x] [Background Blend Mode](https://tailwindcss.com/docs/background-blend-mode)

Filters

- [x] [Blur](https://tailwindcss.com/docs/blur)
- [x] [Brightness](https://tailwindcss.com/docs/brightness)
- [x] [Contrast](https://tailwindcss.com/docs/contrast)
- [x] [Drop Shadow](https://tailwindcss.com/docs/drop-shadow)
- [x] [Grayscale](https://tailwindcss.com/docs/grayscale)
- [x] [Hue Rotate](https://tailwindcss.com/docs/hue-rotate)
- [x] [Invert](https://tailwindcss.com/docs/invert)
- [x] [Saturate](https://tailwindcss.com/docs/saturate)
- [x] [Sepia](https://tailwindcss.com/docs/sepia)
- [x] [Backdrop Blur](https://tailwindcss.com/docs/backdrop-blur)
- [x] [Backdrop Brightness](https://tailwindcss.com/docs/backdrop-brightness)
- [x] [Backdrop Contrast](https://tailwindcss.com/docs/backdrop-contrast)
- [x] [Backdrop Grayscale](https://tailwindcss.com/docs/backdrop-grayscale)
- [x] [Backdrop Hue Rotate](https://tailwindcss.com/docs/backdrop-hue-rotate)
- [x] [Backdrop Invert](https://tailwindcss.com/docs/backdrop-invert)
- [x] [Backdrop Opacity](https://tailwindcss.com/docs/backdrop-opacity)
- [x] [Backdrop Saturate](https://tailwindcss.com/docs/backdrop-saturate)
- [x] [Backdrop Sepia](https://tailwindcss.com/docs/backdrop-sepia)

Tables

- [x] [Border Collapse](https://tailwindcss.com/docs/border-collapse)
- [x] [Table Layout](https://tailwindcss.com/docs/table-layout)

Transitions & Animation

- [x] [Transition Property](https://tailwindcss.com/docs/transition-property)
- [x] [Transition Duration](https://tailwindcss.com/docs/transition-duration)
- [x] [Transition Timing Function](https://tailwindcss.com/docs/transition-timing-function)
- [x] [Transition Delay](https://tailwindcss.com/docs/transition-delay)
- [ ] [Animation](https://tailwindcss.com/docs/animation)

Transforms

- [x] [Scale](https://tailwindcss.com/docs/scale)
- [x] [Rotate](https://tailwindcss.com/docs/rotate)
- [x] [Translate](https://tailwindcss.com/docs/translate)
- [x] [Skew](https://tailwindcss.com/docs/skew)
- [x] [Transform Origin](https://tailwindcss.com/docs/transform-origin)

Interactivity

- [x] [Accent Color](https://tailwindcss.com/docs/accent-color)
- [x] [Appearance](https://tailwindcss.com/docs/appearance)
- [x] [Cursor](https://tailwindcss.com/docs/cursor)
- [x] [Caret Color](https://tailwindcss.com/docs/caret-color)
- [x] [Pointer Events](https://tailwindcss.com/docs/pointer-events)
- [x] [Resize](https://tailwindcss.com/docs/resize)
- [x] [Scroll Behavior](https://tailwindcss.com/docs/scroll-behavior)
- [x] [Scroll Margin](https://tailwindcss.com/docs/scroll-margin)
- [x] [Scroll Padding](https://tailwindcss.com/docs/scroll-padding)
- [x] [Scroll Snap Align](https://tailwindcss.com/docs/scroll-snap-align)
- [x] [Scroll Snap Stop](https://tailwindcss.com/docs/scroll-snap-stop)
- [x] [Scroll Snap Type](https://tailwindcss.com/docs/scroll-snap-type)
- [x] [Touch Action](https://tailwindcss.com/docs/touch-action)
- [x] [User Select](https://tailwindcss.com/docs/user-select)
- [x] [Will Change](https://tailwindcss.com/docs/will-change)

SVG

- [x] [Fill](https://tailwindcss.com/docs/fill)
- [x] [Stroke](https://tailwindcss.com/docs/stroke)
- [x] [Stroke Width](https://tailwindcss.com/docs/stroke-width)

Accessibility

- [ ] [Screen Readers](https://tailwindcss.com/docs/screen-readers)

**Comment by nandorojo** [comment]
how would gap work since RN doesn't have it?

**Comment by marklawlor** [comment]
@nandorojo Correct. While RN doesn't support it, RNW does via the new className styling. The plan is to warn the user when they are using a class name not supported by the current platform.

As I'm working through this list I'm also "fixing" styles that can be supported via polyfills or fallbacks. Eg `aspectRatio` is supported by RN, but other libraries disable it because it's not 100% compatible, but I support it via a small polyfill.

I'm only doing basic polyfills for now, but I've got some more advanced ones planned in the future.

**Comment by marklawlor** [comment]
While I don't yet have 100% coverage, its high enough to give me confidence that the things are working as they should. There's still room for a lot of features but they can come with time.
