### ISSUE TITLE
[Bug] Ignoring components doesn't check allowModules?

### ISSUE THREAD

**Issue by jmeistrich** [marklawlor/tailwindcss-react-native#23]
Referencing https://github.com/marklawlor/tailwindcss-react-native/issues/16:

The ignoring components feature is great, and means we are now able to start fully using this library! But it's not quite there yet for our usage on web. I have made a little patch on our end that makes it usable so we will start to use it! 🎉 

I may be missing something, but these are the issues we are having with it, and note this is on web:
1. `isAllowedProgramPath` appears to only check `allowRelativeModules`, and does not check `allowModules` or `blockModules`?
2. `allowModules` would need to override `allowRelativeModules`. We have separate paths in the tailwind config for the web/rn modules, so implicitly allowing the web modules defeats the purpose.
3. `blockModules` appears to be used in `native-visitor` but not in `web`?

**Comment by marklawlor** [comment]
Fixed in `0.0.27`. Sorry about that must have overlooked it. I've updated the unit tests for web to include these cases

**Comment by jmeistrich** [comment]
@marklawlor Perfect. Thank you!
