### ISSUE TITLE
[Bug] Forwarding className to child doesn't work

### ISSUE THREAD

**Issue by jmeistrich** [marklawlor/tailwindcss-react-native#28]
If I pass `className` into a component which then passes that `className` down to a child component, it does not seem to be processed.

In this example, RNComponent is passed "font-bold" in the `className` prop, but the second Text component renders with no `className`.

```jsx
export function RNComponent({ className }){
    return (
      <>
        <Text className="font-bold">RN component</Text>
        <Text className={className}>RN component with className prop</Text>
      </>
    );
}
...
<RNComponent className="font-bold" />
```

I've updated my repo with a repro for that: https://github.com/jmeistrich/tailwindcss-react-native-next

**Comment by marklawlor** [comment]
This is expected behaviour, as the className prop is removed at compile time

```diff
-     <Text className="font-bold">Test</Text>
+     <Text style={useTailwind("font-bold")}>Test</Text>
```

If you wish to pass the styles to child components you should forward the `style` prop. I'll updating the troubleshooting guide with more info

**Comment by jmeistrich** [comment]
Oh right, that makes sense. Thanks.
