### ISSUE TITLE
[Bug] Cannot find module '@babel/types'

### ISSUE THREAD

**Issue by jmeistrich** [marklawlor/tailwindcss-react-native#41]
After installing into a fresh Next.js project I get this error:

`Error: [BABEL]: Cannot find module '@babel/types'`

Adding it as a devDependency fixes it. That should be in the installation steps or this library's dependency on that should be cleared up?

I have a branch here if you can't reproduce it: https://github.com/jmeistrich/tailwindcss-react-native-next/tree/babelTypesCrash

**Comment by marklawlor** [comment]
Should be fixed in `v1.0.3`
