### ISSUE TITLE
[Bug] styled issues with Animated components

### ISSUE THREAD

**Issue by jmeistrich** [marklawlor/tailwindcss-react-native#45]
On web with `preview` enabled, if I wrap Animated components with `styled`, then the `style` prop has no effect, and there is an error within styleq:

`styleq: width typeof 100 is not "string". `

```jsx
const StyledView = styled(Animated.View);
const StyledText = styled(Animated.Text);

export default function App(props) {
  return (
    <TailwindProvider platform="web" preview>
      <View style={styles.container}>
        <StyledView
          className="p-4 mt-4 bg-gray-800 rounded-lg"
          style={{ width: 100, backgroundColor: 'blue' }}
        >
          <StyledText className="font-bold text-white">
            React Native component
          </StyledText>
        </StyledView>
      </View>
    </TailwindProvider>
  );
}
```

The error goes away if I change it to `styled(View)` or remove the `preview` prop.

I'm not sure if it's something you can fix or if it's something in `react-native-web`?

I updated my test repo with this: https://github.com/jmeistrich/tailwindcss-react-native-next/. But I think it should be easy to reproduce with the code above.

**Comment by marklawlor** [comment]
I'll have a look at it. From that error my gut feeling is that I'm mixing up the precompiled and inline styled objects.

I'm also not 100% sure that Animated works with RNW 0.18 yet.

**Comment by jmeistrich** [comment]
Thanks!

Animated does work with RNW 0.18. We're using the same preview version on our docs site (https://legendapp.com/dev/motion/).

**Comment by marklawlor** [comment]
This looks to be an upstream issue with RNW 0.18. I can replicate it in the canary sandbox https://codesandbox.io/s/crazy-chatelet-iq8uq4?file=/src/App.js

**Comment by jmeistrich** [comment]
Great, thanks!

**Comment by jmeistrich** [comment]
Are there any possible workarounds without waiting for react-native-web's fix? I was excited to use our animation library (based on Animated) together with tailwind, and wanted to publish an article about it, but this seems to completely break it on web. I'm happy to do the work and submit a PR if you have an idea to make it work?

**Comment by marklawlor** [comment]
The workaround is the hooks API, but unfortunately that's currently broken on RNW. When that's fixed you'll be able to access the runtime values of the classes.

**Comment by marklawlor** [comment]
@jmeistrich I'm going to close this issue as mark as "Won't fix".  It's an upstream issue with the preview version of RNW and I'm not familiar enough with that project to fix it.

In addition I'm putting support on getting the hooks API working with Web (preview) on hold for the moment (probably until the release of RNW 0.18).

For the hooks API to function with Web (Preview) I need to add a runtime component can turn CSS StyleSheets into React style objects. Which requires answers to questions like, how do the hooks work in SSR or as a React Server Component where we won't have StyleSheet information? Is the performance cost of this worth it?

I think I've got answers to those questions but I'd rather spend the time improving the non-preview features and come back to this issue closer to the release of RNW 0.18

**Comment by jmeistrich** [comment]
@marklawlor That's fair, no worries. I posted a potential fix to RNW in the PR so hopefully they can take that or something like it into the release. And I've got it working well enough for us to use in my RNW fork (https://github.com/jmeistrich/react-native-web/commit/0266076d0cbe2c15417eb4ada78bf4922093cf72).
