### ISSUE TITLE
Property '__useParseTailwind' doesn't exist

### ISSUE THREAD

**Issue by jmeistrich** [marklawlor/tailwindcss-react-native#5]
Hey, I see this is very new, but I love the idea and I'm excited to use it in a new project. 

I'm getting a `Property '__useParseTailwind' doesn't exist` error when adding it to a React Native app, in the iOS simulator. 

It happens both when using the babel plugin as `'tailwindcss-react-native/babel'` or `['tailwindcss-react-native/babel', { platform: 'native' }]`

**Comment by marklawlor** [comment]
Hi! Yes sorry this is still a work in progress. Can you please try version `0.0.11` which resolves a couple of issues.

Unfortunately I don't have immediate access to an iOS simulator, so I won't be able to test it for a little bit. I'm currently just testing with `android` simulator with Expo and on web with `@expo/next-adapter`. 

I'm not sure if it helps but my test repo is https://github.com/marklawlor/solito-tailwind

**Comment by marklawlor** [comment]
Cheers, just watch the repo for releases. I'll tag version 1.0.0 when its stable. 

Just curious - are you using Expo or vanilla react-native?

**Comment by marklawlor** [comment]
@jmeistrich I fixed an issue that caused babel asynchronous builds to produce a similar error message. Can you please try `0.0.14`. That version will also skip trying to transform native elements.

**Comment by jmeistrich** [comment]
Great, it works now! I tried it in `0.0.15`. Now that it works I'll post a few other issues I encountered.
