### ISSUE TITLE
Enhance RN style inheritance capability

### ISSUE THREAD

**Issue by langtube** [marklawlor/tailwindcss-react-native#53]
RN Component [has almost no style inheritance ability](https://reactnative.dev/docs/text#limited-style-inheritance).
On the Web platform, there are [many CSS properties that have the ability to inherit values from parent elements](https://web.dev/learn/css/inheritance/#which-properties-are-inheritable).

For example, implementing a button with an icon on RN platform.
```html
<Pressable className="... text-white">
    <MailIcon className="text-white" />
    <Text className="text-white">Button text</Text>
</Pressable>
```
Need to set the font color on every child element, which is kind of annoying.
The approach I would like.
```html
<Pressable className="... text-white">
    <MailIcon/>
    <Text>Button text</Text>
</Pressable>
```
This is actually the CSS behavior on the Web platform.
I see this library can implement [Styling based on parent state](https://tailwindcss-react-native.vercel.app/tailwind/core-concepts/component), so I was wondering if this library could also enhance RN's inheritance ability.

**Comment by marklawlor** [comment]
I can see the benefit of this, but I think it would need to be opt in. While is it is default for Web, it's not the default of React Native Web which adds a `css-text` class to every `<Text>` element which resets some styles. RWN resets most of its component but _not all inheritable styles_ which unfortunately creates a system where some inheritance works but others will not. Instead of extending that system, I think it would be better to work around it.

My initial thought was to reuse the `component` concept to also work as a modifier.

```tsx
<Pressable className="... component:text-white">
    <MailIcon/>
    <Text>Button text</Text>
</Pressable>
```

This will ensure all components within the context of the `component` will get the `text-white` styles. With the new priority order being `Component Styles -> ClassNames -> Inline Styles`

However this has the consequence that styles may be sent to invalid components. React Native has three types of styles `TextStyle`, `ViewStyle` and `ImageStyle` and not all components can accept all three. So if `<MailIcon />` was one of these components, a developer will start receiving warnings in their console.

Additionally `component` only works when both the parent and the children are wrapped in `styled()` (or transformed via babel). 
So unfortunately it needs to be opt in for both the parent and child.

```tsx
<Pressable className="... component:text-white">
    <MailIcon className="component-inherit" />
    <Text className="component-inherit">Button text</Text>
</Pressable>
```

While this doesn't "solve" your issue (your still putting classNames on all components) it does provide a API that allows for some flexibility 

```tsx

// Now you have a generic Text component that will inherit if it is within a component context
function MyText({ className, ...props }) {
  return <Text className={`component-inherit ${className}`} {...props} />
}

<Pressable className="... component:text-white">
    <MailIcon className="component-inherit" />
    <MyText>Button text</MyText>
</Pressable>
```

Another benefit of this system is that it's opt in - meaning that components not using it can bail out early and keep the same performance. 

Let me know what you think :thinking:

**Comment by marklawlor** [comment]
Another solution is creating a `parent` modifier that applies styles to children (similar to the [Child Combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator)

This will allow this example to work `styled()` and unstyled components; it will also apply to the immediate children (however these children can still pass those styles down)

```tsx
<Pressable className="... parent:text-white">
    <MailIcon/>
    <Text>Button text</Text>
</Pressable>
```

**Comment by marklawlor** [comment]
Version `v1.5.0-next.1` includes the `parent:` variant which allows you to style a components direct children. Documentation is still coming

You can see an example of its use [here](https://github.com/marklawlor/tailwindcss-react-native/blob/aa9b94ba474edd6d9cab4a31756bfe98ab691e06/__tests__/custom-tailwindcss/parent-variant.tsx#L25-L28) and a snapshot of the output [here](https://github.com/marklawlor/tailwindcss-react-native/blob/aa9b94ba474edd6d9cab4a31756bfe98ab691e06/__tests__/custom-tailwindcss/__snapshots__/parent-variant.tsx.snap#L4-L36)

**Comment by langtube** [comment]
Is it possible to style a specified child element?


在 2022年5月18日，13:05，Mark Lawlor ***@***.***> 写道：

﻿

Version v1.5.0-next.1 includes the parent: variant which allows you to style a components direct children. Documentation is still coming

You can see an example of its use here<https://github.com/marklawlor/tailwindcss-react-native/blob/aa9b94ba474edd6d9cab4a31756bfe98ab691e06/__tests__/custom-tailwindcss/parent-variant.tsx#L25-L28> and a snapshot of the output here<https://github.com/marklawlor/tailwindcss-react-native/blob/aa9b94ba474edd6d9cab4a31756bfe98ab691e06/__tests__/custom-tailwindcss/__snapshots__/parent-variant.tsx.snap#L4-L36>

**Comment by marklawlor** [comment]
No, it will style all children. Styles applying only to specified children is a very non-tailwind (and css concept) and is outside the scope of this library. This scope hasn't been finalised yet, but you can read a preview of it [here](https://github.com/marklawlor/tailwindcss-react-native/blob/next/website/docs/guides/goals.mdx).

For your use case - both React Native and Tailwind CSS recommend either expliciting adding the styles or creating a new component. [Tailwind CSS has guide in their docs](https://tailwindcss.com/docs/reusing-styles#using-editor-and-language-features) about this exact scenario.

**Comment by marklawlor** [comment]
After a bit of thought, I think this is the inheritance model I'm going to implement. I believe it covers many basic utility use-cases without straying too far from the RN & Tailwind CSS philosophy and the project goals.

### `group`

Works identical to Tailwind CSS https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state

### `parent` & `parent:`

`parent` works identical to `group` except only applies to all direct children

`parent:` variant that applies that style to all direct children

Example of `parent` working with CSS https://play.tailwindcss.com/tWrJX5Rapi

### `component` & `component:`

Component is documented here https://tailwindcss-react-native.vercel.app/tailwind/core-concepts/component#component-

`component:` is a variant that works similar to `parent:` but applies to all components within the context with a `inherit:component` className.

I'm also considering `inherit-{pseudoClass}:component` that allows a component to extend an existing component's context.

Example of `component` working with CSS https://www.npmjs.com/package/tailwindcss-nested-groups

---

A quick list of what is already implemented

- [ ] `group`
- [ ] `parent`
- [x] `parent:`
- [x] `component`
- [ ] `component:`

As relying on inheritance is not really recommended by both RN and Tailwind CSS, I don't think these should be common tools used. But they do have niche uses in styling dynamic or 3rd party components.

**Comment by langtube** [comment]
> Is it possible to style a specified child element? className="... icon:h-4"

This is expected to be implemented similarly to CSS [Child Combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator)
```css
div > span {
  background-color: yellow;
}
```
And similar to the implementation of [this tw plugin](https://github.com/SamGoody/tailwind-children) 
```html
<div class="child-p:shadow">
    <p>Shadow</p>
    <a>No Shadow</a>
</div>
```
Yes, this is beyond the scope of inheritance.

**Comment by marklawlor** [comment]
Thanks, that explains it better. I still think it's possibly too complex for RN - at least at this stage in development. However if you want to open a PR I'd gladly review it.

After I've finished the project goals, I'll be releasing some contributing guides that break down the project and show how features are implemented.

**Comment by langtube** [comment]
Yes, it is related to `styling dynamic` .
On RN, sometimes more than one calculation method is needed.

`getContainerStyle`
`getLableStyle`
`getIconStyle`

The `icon` and `label` have some of the same styles and some of their own styles.
So my expectation is that they can be inherited and specified separately.
 
I can imagine an API like this
``` 
<Pressable className="... component:text-white component-icon:h-4" >
    <MailIcon className="component-inherit component-inherit-icon" />
    <Text  className="component-inherit">Button text</Text>
</Pressable>
```

**Comment by langtube** [comment]
> After I've finished the project goals, I'll be releasing some contributing guides that break down the project and show how features are implemented.

This project is very cool.
Hopefully I can make some contribution.

**Comment by marklawlor** [comment]
I think your example is starting to stray to far away from normal styling and could be more cleanly implemented with a component. I have a upcoming API change to the `styled()` hoc to make this kind of thing possible.

```tsx
const PressableIcon = styled(({ icon: Icon, children, iconStyle, textStyle ...props }) {
  return (
    <Pressable { ...props }>
      <Icon style={iconStyle} />
      <Text style={textStyle}>{children}</Text>
    </Pressable>
  )
}, { props: ["className", "iconStyle", "textStyle"] })

<PressableIcon icon={MailIcon} iconStyle="h-4" textStyle="text-white">Button Text</PressableIcon>
```

The upcoming feature allows you to have more than one prop with tailwind based styles. I'm finalizing it now, just working out the Typescript types.

**Comment by langtube** [comment]
Wow
```
const PressableIcon = styled(({ icon: Icon, children, iconStyle, textStyle ...props }) {
  return (
    <Pressable { ...props }>
      <Icon style={iconStyle} />
      <Text style={textStyle}>{children}</Text>
    </Pressable>
  )
}, { props: ["className", "iconStyle", "textStyle"] })

<PressableIcon icon={MailIcon} iconStyle="h-4" textStyle="text-white">Button Text</PressableIcon>
```
This reminds me of the way Tailwind UI implements component variants.
More loosely coupled. 
A much simpler way than `styling dynamic`.

**Comment by marklawlor** [comment]
Tracking this via https://github.com/marklawlor/tailwindcss-react-native/issues/76
