### ISSUE TITLE
Preview: Manual control of Dark mode 

### ISSUE THREAD

**Issue by marklawlor** [marklawlor/tailwindcss-react-native#55]
https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually

**Comment by marklawlor** [comment]
`useColorScheme` was released in `v1.5.0`. https://tailwindcss-react-native.vercel.app/api/use-color-scheme

This allows manual control of the color scheme. 

However manual control with `preview` is still pending.

**Comment by marklawlor** [comment]
Your `useColorScheme` hook is outside the `TailwindProvider`, so it cannot modify the color scheme within the `TailwindProvider` context.

A fix would be

```tsx
export default function App() {

  return (
    <TailwindProvider initialColorScheme={colorScheme}>
      <MyApp />
    </TailwindProvider>
  );
}
  
function MyApp() {
  const { colorScheme, setColorScheme } = useColorScheme();
    
  return (
    <View className="items-center justify-center flex-1 bg-white dark:bg-black">
      <Text className="text-black dark:text-white">
        Tailwindcss react native is working. But dark mode not yet...
      </Text>
      <Text
        onPress={() =>
          setColorScheme(colorScheme === "light" ? "dark" : "light")
        }
      >
        {`The color scheme is ${colorScheme}`}
      </Text>
      <StatusBar style="auto" />
    </View>
  )
}
```

**Comment by ammarfaris** [comment]
Thanks @marklawlor for your swift help.  However, the colorScheme from useColorScheme hook does not seem to reflect the changes of dark/light mode from the system/device  itself. Is this by design? or maybe i'm doing it wrong.

I tried using useColorScheme hook  from "react native"  and inject the current system color scheme into the initialColorScheme of TailwindProvider, it works but only for the first mount. Is there a way to re-assign initialColorScheme so that it can use the useColorScheme hook  from "react native"  everytime there's changes of dark/light mode from the system/device itself?

Thanks in advance!

**Comment by marklawlor** [comment]
In the current version, the library will default (and react to) the systems color scheme, but using `initialColorScheme` switches it to manual control. `useColorScheme` is only for manual control.

In the next major the color scheme can be switched between three states `light, dark & system` allowing you to switch between manual and automatic control. `useColorScheme` will retrieve the live value

**Comment by ammarfaris** [comment]
I see.. thanks @marklawlor... Can't wait for the next major release for the support of the three states `light, dark & system`, that will be awesome!

How do I get the current default behavior for system color scheme, though?

Should the tailwind `dark:` prefix work out of the box?

```javascript
import { StatusBar } from "expo-status-bar";
import { Text, View } from "react-native";
import { TailwindProvider } from "tailwindcss-react-native";

export default function App() {
  return (
    <TailwindProvider>
      <MainApp />
    </TailwindProvider>
  );
}

function MainApp() {
  return (
    <View className="items-center justify-center flex-1 bg-white dark:bg-black">
      <Text className="text-center text-black dark:text-white">
        Tailwindcss react native is working with partial DarkMode setup.
      </Text>
      <StatusBar style="auto" />
    </View>
  );
}
```

do I need to add `darkMode: 'media'` in tailwind.config.js or just omit  `darkMode: 'media'` /  `darkMode: 'class'`  all together ? (but that does not seem to make it work either)
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: 'media', // or 'class' or false
  theme: {
    extend: {},
  },
  plugins: [],
}
```

Again, thanks for your assistance.

**Comment by marklawlor** [comment]
You need to omit `darkMode` from your config altogether. If it's still not working, can you please push a public repo with your code.

**Comment by ammarfaris** [comment]
> You need to omit `darkMode` from your config altogether. If it's still not working, can you please push a public repo with your code.

Here is the public repo of my attempt: [https://github.com/ammarfaris/twcrn-app-ts]

The file AppManual.tsx is just to try to load the system color scheme on the first load, then enable manual control thereafter.

On a different note, is the solito monorepo that includes tailwindcss-react-native coming soon? i'm very new to monorepos.

**Comment by marklawlor** [comment]
Tracking this issue via https://github.com/marklawlor/tailwindcss-react-native/issues/76
