### ISSUE TITLE
Module '"tailwindcss-react-native"' has no exported member 'TailwindProvider' after adding Typescript declaration file

### ISSUE THREAD

**Issue by thespacemanatee** [marklawlor/tailwindcss-react-native#58]
Firstly, thank you for this amazing library!

Following instructions here: https://tailwindcss-react-native.vercel.app/compilation/babel gives me this error.

![Screenshot 2022-05-25 at 10 54 36 PM](https://user-images.githubusercontent.com/6837599/170292577-de6d9a41-4efa-4d7a-9d5f-90b364adae06.png)

**Comment by marklawlor** [comment]
Hi @thespacemanatee, I created a new project following the [quick-start guide](https://tailwindcss-react-native.vercel.app/quick-start) (selecting `with-typescript` from the examples) but was unable to reproduce your issue.

Can you please create a new project following the quick-start guide and verify if the issue persists? If it does, can you please push the code to a public repo and include what version of Typescript you are using.

**Comment by thespacemanatee** [comment]
@marklawlor did you also try creating `tailwindcss-react-native.d.ts` with `import "tailwindcss-react-native/types.d";` in sec directory? I managed to get `className` working with this but every other export is not showing up.

**Comment by marklawlor** [comment]
Yes, the was what I was explicitly testing for. I tried different Typescript setups as well.

Can you please create a public repo that has this issue so I can debug it further.

**Comment by thespacemanatee** [comment]
@marklawlor renamed `tailwindcss-react-native.d.ts` to anything else e.g. `tailwindcss.d.ts` and the problem no longer shows up. I think the documentation should be updated to not use the same name as the library as the filename, else the compiler does not pickup types from the library itself. Feel free to close this issue!

**Comment by thespacemanatee** [comment]
@marklawlor I have added a repro https://github.com/thespacemanatee/tailwind-issue-60 that also includes this typescript declaration issue, feel free to look at it if you have the time!

**Comment by marklawlor** [comment]
This is because of your use of Typescript Paths 

```
"paths": {
      "*": ["src/*"]
      "tests": ["./tests/*"]
},
```

You are configuring every import to first look in the "src" directory before checking other locations. So you are overriding the import for `tailwindcss-react-native` to only look at the `tailwindcss-react-native.d.ts` file and not the module in your `node_modules`.

Is is an issue with your configuration. For example if you have a file called `react.ts` in your src folder, your project will now load that file instead of `node_modules/react`.

**Comment by thespacemanatee** [comment]
@marklawlor thank you, we learn something new every day. Removing this actually solved some other issues I had with auto-imports as well!
