### ISSUE TITLE
[Bug] Styled components unmount/mount every render

### ISSUE THREAD

**Issue by jmeistrich** [marklawlor/tailwindcss-react-native#68]
Using `className` on a styled component causes that component to unmount/mount every time its parent re-renders. If it does not have a `className` it does not re-mount.

App:
```jsx
export default function App() {
  const [state, setState] = useState(false);
  useInterval(() => setState((s) => !s), 1500);
  return (
    <TailwindProvider>
      <View>
        <Text>Styled component with className keeps mounting:</Text>
        <TestComponent className="bg-white" />
        <Text>Styled component without className does not:</Text>
        <TestComponent />
      </View>
    </TailwindProvider>
  );
}

```
Component:
```jsx
let num = 0;

export const TestComponent = memo(function TestComponent() {
  useEffect(() => {
    console.log("Mount");
    num++;
    return () => console.log("Unmount");
  }, []);

  return (
    <View>
      <Text>Re-mounted {num} times</Text>
    </View>
  );
});
```

I believe the problem is that `StyledComponent` creates a new `styled` which returns a new anonymous function every time, so every render creates a whole new component. I think wrapping it in a `useMemo` would solve the problem, but I'm not sure if that might introduce other problems since it's very core code...

I'll submit a PR with that fix in case that's a good solution.

I have a test repo at: https://github.com/jmeistrich/test-tailwindcss-react-native. It's just the expo template plus this library's basic babel installation steps, with the above component, so it should be easy enough to just paste into your own tests. 

Note that I wrapped the component in memo to make sure the component should not re-render since it has no props, and only the instance with className is re-rendering and re-mounting.

**Comment by marklawlor** [comment]
Good catch, I think useMemo is fine for the short term. Ideally I need to extract the logic from `styled()` into a shared function so it can be reused in `<StyledComponent />`, saving the need to use `useMemo()`
