### ISSUE TITLE
[Feature] Allow classNames attribute to be customisable 

### ISSUE THREAD

**Issue by marklawlor** [marklawlor/tailwindcss-react-native#8]
`className` was chosen as it is the `tailwindcss` default - which provides out of the box editor support. But there are some edge cases where this causes some issues eg 3rd party web components may expect a className prop string

This option should be customisable via:

- [ ] Babel options
- [ ] Per file via comments

**Comment by jmeistrich** [comment]
I think this will be important for me - my app is a mix of react-native-web and reactjs components, and it is currently trying to transform my named reactjs components.

**Comment by marklawlor** [comment]
This is no longer possible under the Components API. A user can write their own `StyledComponent` if they don't want to use `className`

**Comment by marklawlor** [comment]
While possible, this adds a bit of complexity. As a compromise, you can now use either `className` or `tw`.

`tw` was chosen as its already being used by other tailwind react-native libraries and is simular to `sx` which is used by other react libraries.

Released in `0.1.7`
