### ISSUE TITLE
Add a sponsorship option

### ISSUE THREAD

**Issue by sam3d** [marklawlor/tailwindcss-react-native#81]
Hey! I just wanted to say thank you so much 💕 this project is incredible, the DX is awesome, and overall it has saved me so much time

I checked for a sponsorship button on both your profile and the project and couldn't find one. I wouldn't be able to contribute much but it'd be really nice to be able to show a token of gratitude for this project and help support its ongoing development. I'm sure I'm not the only one!

Is this something you'd be interested in?

**Comment by marklawlor** [comment]
That's really flattering :smiling_face_with_three_hearts: Small tokens of gratitude are what drives projects like this forward.

I submitted by tax info to Github, which takes ~1week to process. I'll update this issue when I hear back from Github :+1:

**Comment by marklawlor** [comment]
Approval was quicker than I expected, sponsorship is now available :100:
