### ISSUE TITLE
Issue when using with react-navigation (native stack navigator)

### ISSUE THREAD

**Issue by apetta** [marklawlor/tailwindcss-react-native#82]
I'm facing an issue when combining this package with the [react-navigation](https://reactnavigation.org/) package, when using the [native stack navigator](https://reactnavigation.org/docs/native-stack-navigator/).

It works as expected before adding the navigotor, but not after. I've tried a few different ways of wrapping/nesting the TailwindProvider but no luck. Wondering if anyone has faced a similar issue?

![nativewind_issue](https://user-images.githubusercontent.com/33671231/174434932-1075ef7d-1c84-4247-a282-aa66ae55e794.png)

package.json dependencies:
`{
"dependencies": {
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "expo": "~45.0.0",
    "expo-status-bar": "~1.3.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-web": "0.17.7",
    "tailwindcss": "^3.1.3",
    "tailwindcss-react-native": "^1.7.10"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  }
}`

**Comment by sam3d** [comment]
Despite how it may seem, `Stack` is not actually a child of the `TailwindProvider`, as the element is instantiated in the root. That means it isn't a child of the context. What happens if you try moving it into it's own child component?

```ts
export default function App() {
  return (
    <TailwindProvider>
      <MainView />
    </TailwindProvider>
  );
}

function MainView() {
  const Stack = createNativeStackNavigator();

  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
```

**Comment by marklawlor** [comment]
Hi @apetta, I'm not sure how React Navigation works internally, but I'm assuming its rendering `HomeScreen` outside the `TailwindProvider` context

I would recommend splitting the code into two different components. Keep `TailwindProvider` in your App component, and move the navigation into a new component.

Otherwise can you publish a public repo so I can test?

**Comment by sam3d** [comment]
You need to instantiate `Stack` outside of the App component, as shown here https://reactnavigation.org/docs/hello-react-navigation#creating-a-native-stack-navigator

```ts
// In App.js in a new project

import * as React from 'react';
import { View, Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';

function HomeScreen() {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Home Screen</Text>
    </View>
  );
}

const Stack = createNativeStackNavigator();

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default App;
```

**Comment by apetta** [comment]
> Hi @apetta, I'm not sure how React Navigation works internally, but I'm assuming its rendering `HomeScreen` outside the `TailwindProvider` context
> 
> I would recommend splitting the code into two different components. Keep `TailwindProvider` in your App component, and move the navigation into a new component.
> 
> Otherwise can you publish a public repo so I can test?

@marklawlor  I've given that a go and pulled all the navigation logic to a separate component which is imported into App.js. Unfortunately, no luck! I've pushed a [repo](https://github.com/apetta/rn-tailwind-navigator-test) for you to have a look when you get a sec. Thank you!



> You need to instantiate `Stack` outside of the App component, as shown here https://reactnavigation.org/docs/hello-react-navigation#creating-a-native-stack-navigator
> 


@sam3d  Ah thanks for heads up, didn't fix this issue unfortunately 😞

**Comment by marklawlor** [comment]
@apetta It doesn't appear your `tailwind.config.js` `content` setting covers the new files you created.

**Comment by apetta** [comment]
> @apetta It doesn't appear your `tailwind.config.js` `content` setting covers the new files you created.

Now I feel silly haha, thanks for your help - that was the issue!
