### ISSUE TITLE
Expo unexpected token "{" error

### ISSUE THREAD

**Issue by ochilliam** [marklawlor/tailwindcss-react-native#83]
Hi, thanks for the awesome project.
As soon as I install the project for my expo app, I get `unexpected token "{". import call expects exactly one argument` not sure what's causing it.
![photo](https://user-images.githubusercontent.com/65443737/174443757-f5b3fcdb-c2bf-41e5-a1b3-d24a3693fa3c.png)

 
I'm not sure If it's only happening to me or other people too. couldn't find anything for it so I thought why not creating an issue here in case anyone else had the same error.

Device: macbook pro m1 Monterey 12.4
Node: v16.15.0
Expo:  45
Reproduced example: https://github.com/ochilliam/side-project-goftego

**Comment by vital-tech-results** [comment]
It would be nice ⚛️ if you put your example [on Snack](https://snack.expo.dev) so we could see the code in the browser.

**Comment by marklawlor** [comment]
@ochilliam Are you using the v2 preview? That error can occur when you don't have `content` set in your `tailwind.config.js`. 

v2 is still unstable, I'm hoping to have a stable release candidate by the end of this week.
