### ISSUE TITLE
Custom properties (a.k.a CSS Variables)

### ISSUE THREAD

**Issue by winterscar** [marklawlor/tailwindcss-react-native#87]
One (relatively) popular pattern for allowing for a little bit of runtime configuration of tailwind based apps is to use css vars in conjunction with the theme config.

> tailwind.config.js
```js
module.exports = {
  theme: {
    extend: {
      colors: {
        primary: "var(--primary)",
        secondary: "var(--secondary)",
        main: "var(--main)",
        background: "var(--background)",
        header: "var(--header)",
        accent: "var(--accent)",
      },
    },
  },
};
```

Then, at runtime we can set those variables and allow the user to pick a primary color for example. This pattern doesn't translate well to RN for the simple reason that we don't have css variables. However, we do have the stylesheet, and that is injected into the `TailwindProvider` at runtime.

What could be interesting is to allow for a way to intercept the stylesheet before it's injected into the `TailwindProvider` by babel, transform it (replace colors for example), and then pass it through to the `TailwindProvider`. 

I think this might be possible right now using the Tailwind CLI approach, but I'd love to be able to do it using Babel too.

**Comment by marklawlor** [comment]
CSS custom properties are on the roadmap and will be supported by Babel :100: They won't be in the initial 2.0 release, but new major version was written with features like custom properties in mind.

**Comment by marklawlor** [comment]
I'm going to close this issue and track it via the [Feature Request Project](https://github.com/users/marklawlor/projects/2/views/1).

I like to keep the repo's issues focusing on bugs/problems.

Your welcome to still comment/ask questions. I'll reopen the issue when development has started.

**Comment by langtube** [comment]
I just saw an example of achieving dynamic colors based on  CSS Variables.

In case anyone is interested.

code: https://github.com/fbrill/dynamic-colors-in-tailwind

demo: https://dynamic-colors-in-tailwind-demo.vercel.app/

**Comment by dohomi** [comment]
@marklawlor I realised that this might be related for not being able to use DaisyUI (which uses css vars)
https://github.com/marklawlor/nativewind/discussions/223#discussioncomment-3532819
Are there any workarounds available to set the css vars?

**Comment by dohomi** [comment]
@winterscar how did you solve CSS Vars support with the CLI? In the output of `npx tailwindcss -i global.css --postcss postcss.config.js` the css vars and @media queries are not part of the output.
