### ISSUE TITLE
Not working with `eas build`

### ISSUE THREAD

**Issue by chetankumar01** [marklawlor/tailwindcss-react-native#88]
I have followed the installation steps using `babel`. My app is working perfectly in development. When trying to run in release mode, the app launches with an empty screen.

If I replace:
```
<TailwindProvider>
  <App />
</TailwindProvider>
```
with a simple `<View style={{flex: 1, backgroundColor: "red"}} />`

the app behaves as expected. 

Is there something I am missing?

babel.config.js
```
module.exports = {
  presets: ["module:metro-react-native-babel-preset"],
  plugins: [
    "inline-dotenv",
    "react-native-reanimated/plugin",
    "tailwindcss-react-native/babel",
  ],
};
```

metro.config.js
```
// const { createMetroConfiguration } = require("expo-yarn-workspaces");

// module.exports = createMetroConfiguration(__dirname);

// Learn more https://docs.expo.dev/guides/monorepos
const { getDefaultConfig } = require("expo/metro-config");
const path = require("path");

const projectRoot = __dirname;
const workspaceRoot = path.resolve(projectRoot, "../..");

const config = getDefaultConfig(projectRoot);

config.watchFolders = [workspaceRoot];
config.resolver.nodeModulesPath = [
  path.resolve(projectRoot, "node_modules"),
  path.resolve(workspaceRoot, "node_modules"),
];

module.exports = config;
```

```
"tailwindcss-react-native": "^1.7.10"
```

Adding more info after @jmeistrich comment -

`tailwind.config.js`
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

I am using `eas build` to create builds and `eas update` to release OTA updates. 

The build created by `eas build` has the issue.
If I push an update using `eas update`, the app starts working fine again.

Screenshot development `eas run:ios`
![Simulator Screen Shot - iPhone 8 - 2022-06-24 at 20 19 44](https://user-images.githubusercontent.com/1592571/175570226-f2356f4d-3ba5-4e84-9552-d264405dfa50.png)

Screenshot simulator build `eas build --local`
![Simulator Screen Shot - iPhone 8 - 2022-06-24 at 20 59 48](https://user-images.githubusercontent.com/1592571/175570322-dd7b6b63-d455-4181-9380-c68e4e03d906.png)

Screenshot after ota update `eas update` has been downloaded on simulator
![Simulator Screen Shot - iPhone 8 - 2022-06-24 at 21 05 40](https://user-images.githubusercontent.com/1592571/175570469-e5b5dfe1-67ab-474c-abc7-868e90b8b4d1.png)

**Comment by jmeistrich** [comment]
Did you add the `tailwind.config.js`?

**Comment by chetankumar01** [comment]
Thanks for the prompt response. Yes, I have a `tailwind.config.js`

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  plugins: [],
};
```

**Comment by jmeistrich** [comment]
I don't actually know how to solve it 😆 . I just thought @marklawlor would want to see that.

**Comment by marklawlor** [comment]
@chetankumar01 I'll look at this after the weekend, it sounds like eas might do a production optimisation that breaks the initial load (similar to https://github.com/marklawlor/tailwindcss-react-native/issues/60)

You could also try try testing `nativewind@latest` instead of `tailwindcss-react-native`. It should mostly be a drop-in replacement (a poorly written migration guide is [here](https://tailwindcss-react-native-git-next-mwlawlor.vercel.app/guides/tailwindcss-react-native)). It works slightly differently and might fix your issue.

**Comment by chetankumar01** [comment]
@marklawlor , Thank you for your response. I have upgraded to `nativewind@2.0.0-next.24` and the issue still exists.

**Comment by marklawlor** [comment]
@chetankumar01 I am unable to replicate your issue, can you please create a public repo that demonstrates the issue.

You can also see project I used for testing https://github.com/marklawlor/tailwindcss-react-native-issue-88.

**Comment by a-eid** [comment]
weird, I built a couple of apps that uses this lib using eas and they built fine.

**Comment by chetankumar01** [comment]
@marklawlor , I tried using `styled` component, and still I don't see any styles after building. Do you think the monorepo setup is causing issues?

**Comment by marklawlor** [comment]
@chetankumar01 Can you please create a public repo with a minimal reproduction of the issue. Without seeing your project/folder structure its very difficult to assist you. 

Tailwind CLI only compiles styles that match the content glob, so depending on how your building your project it maybe that the glob is wrong, etc.

**Comment by chetankumar01** [comment]
@marklawlor , I created a new monorepo and it's working. I will try and find what I am doing wrong in my setup. Thank you for your time.

**Comment by kslbdev** [comment]
I am seeing this same exact issue. Was there ever any offline progress made on this?

Something is different about the bundling in the "eas build", styles don't work. Once the app receives an update (created via "expo export"), all styles work fine.

**Comment by Phenome** [comment]
> Something is different about the bundling in the "eas build", styles don't work. Once the app receives an update (created via "expo export"), all styles work fine.

Interestingly, I have the opposite experience. If I push a new build (Android) and update on my phone, styles look good. If I push via eas update, then the styles break 🤷🏻

**Comment by kslbdev** [comment]
Its worth noting i am using nativewind v4. Are you on v2?
