### ISSUE TITLE
Default font family

### ISSUE THREAD

**Issue by JWesorick** [marklawlor/tailwindcss-react-native#93]
Following the directions [here](https://tailwindcss.com/docs/font-family#customizing-the-default-font) I tried to change the default font by setting the `sans` font. The default font with this package seems to still use the original fonts from tailwind instead of the expected defaults set in `tailwind.config.js`.

```css
font: 14px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
```

instead of 
```css 
font: 14px my-custom-font
```

Adding the `font-sans` class will correctly set the custom font, but I'd like to not have to add that all over.

I'm using `1.7.10`

**Comment by marklawlor** [comment]
Those docs only apply to [Tailwind Preflight](https://tailwindcss.com/docs/preflight), which this library does not support. I would like to do something like Preflight for Native, but its not on the immediate roadmap.

React Native has [limited style inheritance](https://reactnative.dev/docs/text#limited-style-inheritance) so it's not possible to simply force a default font on all `<Text />` components. Your best option is to create a custom component

```
export const MyText = ({ className, ...props }) => <Text className={`font-sans ${className}`} {...props} />
```

NativeWind has a convenience method to help create custom components

```
export const MyText = styled(Text, "font-sans")
```

**Comment by JWesorick** [comment]
Thanks! That makes sense.
