### ISSUE TITLE
Border width 1 is not working

### ISSUE THREAD

**Issue by Saad-Bashar** [marklawlor/tailwindcss-react-native#97]
When I use this, RN throws an error. Any idea on this? Also, `className` is giving TS error on `TouchableOpcity`, though it works with View and Text. 

```
<TouchableOpacity className="border" />
```
![Screenshot 2022-06-29 at 12 28 04 PM](https://user-images.githubusercontent.com/13269141/176351869-4675424d-b367-4697-889c-938e3e7efd5d.png)

**Comment by marklawlor** [comment]
Hi @Saad-Bashar, I assume your running `NativeWind`?

Can you please try upgrading to `nativewind@latest`
